//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfByEmail {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SpecialUrl : global::System.Configuration.ApplicationSettingsBase {
        
        private static SpecialUrl defaultInstance = ((SpecialUrl)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SpecialUrl())));
        
        public static SpecialUrl Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=b\"")]
        public string gbusiness {
            get {
                return ((string)(this["gbusiness"]));
            }
            set {
                this["gbusiness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=e\"")]
        public string gentertainment {
            get {
                return ((string)(this["gentertainment"]));
            }
            set {
                this["gentertainment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=h\"")]
        public string gmoretopstories {
            get {
                return ((string)(this["gmoretopstories"]));
            }
            set {
                this["gmoretopstories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&q=replaceme\"")]
        public string gnews {
            get {
                return ((string)(this["gnews"]));
            }
            set {
                this["gnews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=snc\"")]
        public string gscience {
            get {
                return ((string)(this["gscience"]));
            }
            set {
                this["gscience"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=t\"")]
        public string gscitech {
            get {
                return ((string)(this["gscitech"]));
            }
            set {
                this["gscitech"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=s\"")]
        public string gsports {
            get {
                return ((string)(this["gsports"]));
            }
            set {
                this["gsports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=ir\"")]
        public string gspotlight {
            get {
                return ((string)(this["gspotlight"]));
            }
            set {
                this["gspotlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=tc\"")]
        public string gtechnology {
            get {
                return ((string)(this["gtechnology"]));
            }
            set {
                this["gtechnology"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=n\"")]
        public string gus {
            get {
                return ((string)(this["gus"]));
            }
            set {
                this["gus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=w\"")]
        public string gworld {
            get {
                return ((string)(this["gworld"]));
            }
            set {
                this["gworld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"http://stocktwits.com/symbol/replaceme\"")]
        public string stocktwits {
            get {
                return ((string)(this["stocktwits"]));
            }
            set {
                this["stocktwits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://twitter.com/hashtag/replaceme\"")]
        public string twitter {
            get {
                return ((string)(this["twitter"]));
            }
            set {
                this["twitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news/section?pz=1&cf=all&topic=m\"")]
        public string ghealth {
            get {
                return ((string)(this["ghealth"]));
            }
            set {
                this["ghealth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"http://www.nasdaq.com/earnings/earnings-calendar.aspx?date= replaceme\"")]
        public string ercalendar {
            get {
                return ((string)(this["ercalendar"]));
            }
            set {
                this["ercalendar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"http://www.google.com/search?q=replaceme\"")]
        public string g {
            get {
                return ((string)(this["g"]));
            }
            set {
                this["g"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"https://news.google.com/news?pz=1&cf=all&ned=replacemhttps://news.google.com/new" +
            "s?pz=1&cf=all&ned=replaceme\"")]
        public string gtopstories {
            get {
                return ((string)(this["gtopstories"]));
            }
            set {
                this["gtopstories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"http://www.marketwatch.com/investing/multi?tickers=replaceme\"")]
        public string mwquotes {
            get {
                return ((string)(this["mwquotes"]));
            }
            set {
                this["mwquotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"http://www.nasdaq.com/symbol/replaceme/real-time\"")]
        public string quote {
            get {
                return ((string)(this["quote"]));
            }
            set {
                this["quote"] = value;
            }
        }
    }
}
